### ISSUE TITLE
Compilation Prerequisite Details?

### ISSUE THREAD

**Issue by docrjh** [pstolarz/w1-gpio-cl#1]
Hi, This 1-wire bus driver looks exceptionally usefull, if I can get it to work!
I'm trying to get two 1-wire interfaces to run on a Pi Zero without major re-work of the operating system, and your work here looks like exactly whats required.
I tried to run the following via terminal on a freshly installed copy of the latest Rasbian jessie (25/11/16) on a raspberry pi zero;

sudo git clone https://github.com/pstolarz/w1-gpio-cl.git
cd w1-gpio-cl
modprobe wire
sudo make
insmod ./w1-gpio-cl.ko m1="gdt:GPIO1"

However as you can see from the log below, the Make process failed, and w1-gpio-cl.ko was not produced. I guess that this is because I've not provided the prerequisites you mention  in the README. Assuming this is the case, any chance that you could include a more step by step guide in the README? or point out the thing I'm doing wrong?
Many thanks in anticipation!
Richard

***log*** 
pi@raspberrypi:~ $ sudo git clone https://github.com/pstolarz/w1-gpio-cl.git
Cloning into 'w1-gpio-cl'...
remote: Counting objects: 63, done.
remote: Total 63 (delta 0), reused 0 (delta 0), pack-reused 63
Unpacking objects: 100% (63/63), done.
Checking connectivity... done.
pi@raspberrypi:~ $ cd w1-gpio-cl
pi@raspberrypi:/w1-gpio-cl $ modprobe wire
pi@raspberrypi:~/w1-gpio-cl $ sudo make
`gen-mast.h' has been generated.

NOTE: The compiled module needs w1 set of headers, which is a part of the internal
(not the public) part of the w1 API. The headers are contained in the full Linux
kernel source tree.
Since the kernel sources has not been detected on this platform, the compilation
process will use headers which are part of this source bundle (included in
./w1-internal directory). Linux kernel API is not persistent across versions, so
it is STRONGLY recommended to set ./w1 symbolic link to `drivers/w1' subdirectory
of the target kernel sources. This way proper w1 headers will be used.

Press ENTER to continue...
make -C /lib/modules/4.4.34+/build M= modules
make[1]: *** /lib/modules/4.4.34+/build: No such file or directory.  Stop.
Makefile:13: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by pstolarz** [comment]
Hi Richard,
The problem is associated with lack of headers corresponding to the version of kernel you use (4.4.34).
If you want compile the module directly on the platform try this:

- clone kernel src-tree corresponding to your ver of kernel:

    `git clone --depth 1 --branch 38f2800e6e94019a00a2880bfed8fba37aea2e5d https://github.com/raspberrypi/linux`

    NOTE: 38f2800e commit corresponds to 4.4.33 kernel since I don't see 4.4.34 on the [raspberry/firmware](https://github.com/raspberrypi/firmware/commits/master) repo. Should you had have problems with loading the module for this version of kernel src-tree, you may want to check commits later to this commit for compilation.

- compile the module with

    `KERNEL_SRC=<path to kernel src-tree> make`

**Comment by docrjh** [comment]
Hi
Thanks for the very quick reply.
Unfortunately, the clone request came back remote branch not found.  Any ideas?
***log***
pi@raspberrypi:~/w1-gpio-cl $ sudo git clone --depth 1 --branch 38f2800e6e94019a00a2880bfed8fba37aea2e5d https://github.com/raspberrypi/linux
Cloning into 'linux'...
warning: Could not find remote branch 38f2800e6e94019a00a2880bfed8fba37aea2e5d to clone.
fatal: Remote branch 38f2800e6e94019a00a2880bfed8fba37aea2e5d not found in upstream origin

**Comment by pstolarz** [comment]
So try this:

`git clone --branch rpi-4.4.y --depth 1000 https://github.com/raspberrypi/linux`
`cd linux`
`git checkout 38f2800e6e94019a00a2880bfed8fba37aea2e5d`
`export KERNEL_SRC=$(pwd)`
`make bcmrpi_defconfig modules_prepare`

Hope, now you should be able to compile the module by `make` in its directory.

**Comment by docrjh** [comment]
Hi, OK, I  managed to clone linux and the git checkout and export seemed to work but make bcmrpi appears to fail. please see log bellow.

***log***
pi@raspberrypi:~ $ cd linux
pi@raspberrypi:/linux $ sudo git checkout 38f2800e6e94019a00a2880bfed8fba37aea2e5d
HEAD is now at 38f2800... Merge remote-tracking branch 'stable/linux-4.4.y' into rpi-4.4.y
pi@raspberrypi:/linux $ export KERNEL_SRC=$(pwd)
pi@raspberrypi:~/linux $ sudo make bcmrpi_defconfig modules_prepare
#
# configuration written to .config
#
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
make[2]: 'include/generated/mach-types.h' is up to date.
  CHK     include/generated/bounds.h
  CHK     include/generated/timeconst.h
/bin/sh: 1: bc: not found
Kbuild:66: recipe for target 'include/generated/timeconst.h' failed
make[2]: *** [include/generated/timeconst.h] Error 127
Makefile:1003: recipe for target 'prepare0' failed
make[1]: *** [prepare0] Error 2
Makefile:520: recipe for target '__build_one_by_one' failed
make: *** [__build_one_by_one] Error 2

cd to w1-gpio-cl dir
pi@raspberrypi:/w1-gpio-cl $ sudo KERNEL_SRC=/home/pi/linux make
`gen-mast.h' has been generated.
make -C /home/pi/linux M= modules
make[1]: Entering directory '/home/pi/linux'
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
make[2]: 'include/generated/mach-types.h' is up to date.
  CHK     include/generated/bounds.h
  CHK     include/generated/timeconst.h
/bin/sh: 1: bc: not found
Kbuild:66: recipe for target 'include/generated/timeconst.h' failed
make[2]: *** [include/generated/timeconst.h] Error 127
Makefile:1003: recipe for target 'prepare0' failed
make[1]: *** [prepare0] Error 2
make[1]: Leaving directory '/home/pi/linux'
Makefile:13: recipe for target 'all' failed
make: *** [all] Error 2
pi@raspberrypi:~/w1-gpio-cl $

**Comment by pstolarz** [comment]
As stated in README `bc` is required to build the module/kernel. Install its package.
`sudo apt-get install bc`

**Comment by pstolarz** [comment]
README has been updated. If more info is needed reopen the issue or provide your pull request.
