### ISSUE TITLE
Modify timeout value for 1W device scan

### ISSUE THREAD

**Issue by przemoch-dev** [pstolarz/w1-gpio-cl#5]
Hey,

I'm using this driver on my Jetson Nano computer to work with W1 devices. It has `w1_master_timeout` value set to 10 s by default. It is too little, and I would like to change this value to 1 s. Could you pls tell me how to configure it?

**Comment by pstolarz** [comment]
https://raspberrypi.stackexchange.com/questions/15333/force-detection-of-gpio-device-connection-disconnection

For the future - please use google before rising an issue.

**Comment by przemoch-dev** [comment]
Yes, I used google and saw this thread. Unfortunately both methods described do not work. 
```
cat /sys/bus/w1/drivers/w1_master_driver/w1_bus_master1/w1_master_timeout
10
```

I set proper option to the `/etc/modprobe.d/w1.conf ` and result is the same, however I can see my modification in the modprobe config
```
$ modprobe -c | grep wire
options wire timeout=1 slave_ttl=3
```

That's where my question comes from (forgive the overly vague description), can this be changed by configuring the driver you provide?

**Comment by przemoch-dev** [comment]
Nvm, I did patch for linux-tegra w1.c with my values and recompiled it. Thank you and sorry for bothering you

**Comment by pstolarz** [comment]
If you use 1-wire for reading-out dallas temp sensors I recommend to discard the `w1_therm` module and use my userland [librasp](https://github.com/pstolarz/librasp). It's much more powerful and feature-rich (not only in case of bus-scanning). Some knowledge about C programming is required, though, to port it into your platform (it was originally written for RPi), but the netlink interface used for kernel-userland communication remains the same for all Linux platforms.
